language:
  - cpp

compiler:
  - gcc
  
before_install:
  - sudo apt-get update

install:

  - sudo apt-get install qtbase5-dev avconv build-essential cmake libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
  - sudo apt-get install -y build-essential cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev

  - curl -sL https://github.com/opencv/opencv/archive/3.2.0.zip > opencv.zip
  - unzip opencv.zip
  - cd 3.2.0
  
  # Create a new 'build' folder.
  - mkdir build
  - cd build
  
  # Set build instructions for Ubuntu distro.
  - cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D WITH_TBB=OFF -D BUILD_NEW_PYTHON_SUPPORT=OFF -D WITH_V4L=ON -D INSTALL_C_EXAMPLES=ON -D INSTALL_PYTHON_EXAMPLES=OFF -D BUILD_EXAMPLES=ON -D WITH_QT=ON -D WITH_OPENGL=ON ..
  
  # Run 'make' with four threads.
  - make -j4
  
  # Install to OS.
  - sudo make install
  
  # Add configuration to OpenCV to tell it where the library files are located on the file system (/usr/local/lib)
  - sudo sh -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/opencv.conf'
  
  - sudo ldconfig
  - echo "OpenCV installed."
  
  # We need to return to the repo "root" folder, so we can then 'cd' into the C++ project folder.
  - cd ../../

script:
  - cd [project_dir]
  - cmake .
  - qmake -qt=qt5 -v
  - make
  - ./[application_name] [params]